/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test_package;

/**
 *
 * @author manub
 */

        import javax.swing.JOptionPane;
        import logic.AuthValidator;
        import logic.LoginResult;
        import logic.User;

public class LOG_IN extends javax.swing.JFrame {

    
   public LOG_IN() {
        initComponents();
        setLocationRelativeTo(null);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LOG_INBTN = new javax.swing.JButton();
        REGISTERBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        REGISTER = new javax.swing.JLabel();
        USER_NAME = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOG_INBTN.setBackground(new java.awt.Color(0, 0, 0));
        LOG_INBTN.setFont(new java.awt.Font("Sitka Display", 1, 12)); // NOI18N
        LOG_INBTN.setForeground(new java.awt.Color(255, 255, 255));
        LOG_INBTN.setText("LOG IN");
        LOG_INBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOG_INBTNActionPerformed(evt);
            }
        });
        jPanel1.add(LOG_INBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 80, -1));

        REGISTERBTN.setBackground(new java.awt.Color(0, 0, 0));
        REGISTERBTN.setFont(new java.awt.Font("Sitka Display", 1, 12)); // NOI18N
        REGISTERBTN.setForeground(new java.awt.Color(255, 255, 255));
        REGISTERBTN.setText("REGISTER");
        REGISTERBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTNActionPerformed(evt);
            }
        });
        jPanel1.add(REGISTERBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 40, 20));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, 20));

        REGISTER.setForeground(new java.awt.Color(255, 255, 255));
        REGISTER.setText("you dont jave account?Register here!");
        jPanel1.add(REGISTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, 10));

        USER_NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USER_NAMEActionPerformed(evt);
            }
        });
        jPanel1.add(USER_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 190, 30));
        jPanel1.add(PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 190, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USER_NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USER_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USER_NAMEActionPerformed

    private void LOG_INBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOG_INBTNActionPerformed
    
     String username = USER_NAME.getText().trim();
    String password = new String(PASSWORD.getPassword());

    // Validation
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Please enter username and password",
            "Validation Error",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Authenticate
    LoginResult result = AuthValidator.login(username, password);

    if (!result.success) {
        JOptionPane.showMessageDialog(this,
            result.message,
            "Login Failed",
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Redirect based on role
    User user = result.user;

    if (user.role == User.Role.ADMIN) {
        new ADMIN_DASH(user).setVisible(true);
    } else {
        new CASHIER_DASH(user).setVisible(true);
    }

    this.dispose();



    }//GEN-LAST:event_LOG_INBTNActionPerformed

    private void REGISTERBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTNActionPerformed
         REGISTER_DASH registerDash = new REGISTER_DASH();
         registerDash.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_REGISTERBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOG_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOG_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOG_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOG_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOG_IN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOG_INBTN;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JLabel REGISTER;
    private javax.swing.JButton REGISTERBTN;
    private javax.swing.JTextField USER_NAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
