/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test_package.ADMIN;

import db.DBConnection;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import model.Product;
import dao.ProductDao;
import logic.User;
import util.AppUI;

public class MANAGE_PRODUCT_DASH extends javax.swing.JFrame {
    private User currentUser;

    /**
     * Creates new form MANAGE_PRODUCT_DASH
     */
    public MANAGE_PRODUCT_DASH() {
        this(null);
    }
    
    public MANAGE_PRODUCT_DASH(User user) {
        this.currentUser = user;
        initComponents();
        AppUI.setupFrame(this, "Coffee Shop POS - Manage Products", true);
        AppUI.styleTable(productTable);
        AppUI.setPlaceholder(txtName, "e.g. Cappuccino");
        AppUI.setPlaceholder(txtCategory, "e.g. Hot Coffee");
        AppUI.setPlaceholder(txtPrice, "e.g. 4.50");
        AppUI.setPlaceholder(txtStock, "e.g. 100");
        AppUI.makeSecondary(btnBack);
        AppUI.makeSecondary(btnDelete);
        AppUI.makeSecondary(btnUpdate);
        AppUI.makePrimary(btnAdd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadProducts() {
        loadProducts("");
    }

    private void loadProducts(String keyword) {
        try {
            DefaultTableModel tableModel = (DefaultTableModel) productTable.getModel();
            tableModel.setRowCount(0);
            List<Product> products = ProductDao.getAllProducts();
            for (Product p : products) {
                if (keyword.isEmpty() || String.valueOf(p.id).contains(keyword)) {
                    tableModel.addRow(new Object[]{p.id, p.name, p.category, p.price, p.stock,
                        p.isAvailable ? "Available" : "Unavailable"});
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading products: " + e.getMessage());
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"ID", "Name", "Category", "Price", "Stock", "Status"}
        ) {
            boolean[] canEdit = new boolean [] {false, false, false, false, false, false};
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 540, 300));

        // Search bar
        javax.swing.JLabel lblSearch = new javax.swing.JLabel("Search ID:");
        lblSearch.setFont(new java.awt.Font("Sitka Display", 1, 13));
        lblSearch.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 25));
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 30, 280, 25));

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Sitka Display", 1, 12));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(evt -> loadProducts(txtSearch.getText().trim()));
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 30, 90, 25));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Category:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Display", 1, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stock:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 180, -1));
        jPanel1.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 180, -1));
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 180, -1));
        jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 180, -1));

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Sitka Display", 1, 12));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 90, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Sitka Display", 1, 12));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 90, -1));

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setFont(new java.awt.Font("Sitka Display", 1, 12));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("ARCHIVE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 90, -1));

        btnToggleAvail = new javax.swing.JButton();
        btnToggleAvail.setBackground(new java.awt.Color(0, 102, 51));
        btnToggleAvail.setFont(new java.awt.Font("Sitka Display", 1, 11));
        btnToggleAvail.setForeground(new java.awt.Color(255, 255, 255));
        btnToggleAvail.setText("TOGGLE AVAIL");
        btnToggleAvail.addActionListener(evt -> btnToggleAvailActionPerformed(evt));
        jPanel1.add(btnToggleAvail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 140, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Sitka Display", 1, 12));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 90, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png")));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
        loadProducts();
    }// </editor-fold>//GEN-END:initComponents

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {
        int row = productTable.getSelectedRow();
        txtName.setText(productTable.getValueAt(row, 1).toString());
        txtCategory.setText(productTable.getValueAt(row, 2) != null ? productTable.getValueAt(row, 2).toString() : "");
        txtPrice.setText(productTable.getValueAt(row, 3).toString());
        txtStock.setText(productTable.getValueAt(row, 4).toString());
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String name = txtName.getText().trim();
            String category = txtCategory.getText().trim();
            double price = Double.parseDouble(txtPrice.getText().trim());
            int stock = Integer.parseInt(txtStock.getText().trim());
            
            if (name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Product name is required!");
                return;
            }
            
            ProductDao.addProduct(name, category.isEmpty() ? null : category, price, stock);
            JOptionPane.showMessageDialog(this, "Product added successfully!");
            loadProducts();
            txtName.setText("");
            txtCategory.setText("");
            txtPrice.setText("");
            txtStock.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for price and stock!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int row = productTable.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Please select a product to update");
                return;
            }
            
            int id = (int) productTable.getValueAt(row, 0);
            String name = txtName.getText().trim();
            String category = txtCategory.getText().trim();
            double price = Double.parseDouble(txtPrice.getText().trim());
            int stock = Integer.parseInt(txtStock.getText().trim());
            
            if (name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Product name is required!");
                return;
            }
            
            ProductDao.updateProduct(id, name, category.isEmpty() ? null : category, price, stock);
            JOptionPane.showMessageDialog(this, "Product updated successfully!");
            loadProducts();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for price and stock!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void btnToggleAvailActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int row = productTable.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Please select a product to toggle availability.");
                return;
            }
            int id = (int) productTable.getValueAt(row, 0);
            String currentStatus = productTable.getValueAt(row, 5).toString();
            String newStatus = currentStatus.equals("Available") ? "Unavailable" : "Available";
            int confirm = JOptionPane.showConfirmDialog(this,
                "Mark this product as " + newStatus + "?", "Toggle Availability", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                ProductDao.toggleAvailability(id);
                loadProducts(txtSearch.getText().trim());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int row = productTable.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Please select a product to archive");
                return;
            }
            
            int id = (int) productTable.getValueAt(row, 0);
            int confirm = JOptionPane.showConfirmDialog(this, "Archive this product?");
            if (confirm == JOptionPane.YES_OPTION) {
                ProductDao.deleteProduct(id);
                JOptionPane.showMessageDialog(this, "Product archived successfully!");
                loadProducts();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
        new test_package.ADMIN_DASH(currentUser).setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        AppUI.initLookAndFeelOnce();
        java.awt.EventQueue.invokeLater(() -> {
            User demo = new User(0, "admin", User.Role.ADMIN);
            new MANAGE_PRODUCT_DASH(demo).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnToggleAvail;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JButton btnSearch;
    // End of variables declaration//GEN-END:variables
}
